name: Build Matrix
author: Alexander Druz
description: GitHub action to create a reusable and potentially dynamic matrix for workflow jobs.
branding:
  icon: layers
  color: gray-dark
inputs:
  matrix:
    default: ''
    description: Base matrix
  include:
    default: ''
    description: Extra matrix combinations to include
  exclude:
    default: ''
    description: Matrix combinations to exclude from matrix
outputs:
  matrix:
    description: matrix in JSON format
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: composite
  steps:
    - name: Set matrix
      id: set-matrix
      run: dist/build-matrix.sh "${{ inputs.matrix }}" "${{ inputs.include }}" "${{ inputs.exclude }}"
      # run: |
      #   MATRIX="$(dist/build-matrix.sh "${{ inputs.matrix }}" "${{ inputs.include }}" "${{ inputs.exclude }}")" \
      #     || echo "$MATRIX"; exit 1
      shell: bash
