name: Build Matrix
author: Alexander Druz
description: GitHub action to create a reusable and potentially dynamic matrix for workflow jobs.
branding:
  icon: layers
  color: gray-dark
inputs:
  matrix:
    default: ''
    description: Base matrix
  exclude:
    default: ''
    description: Matrix combinations to exclude from matrix
  include:
    default: ''
    description: Extra matrix combinations to include
outputs:
  matrix:
    description: matrix in JSON format
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: composite
  steps:
    - name: Set matrix
      id: set-matrix
      run: |
        INPUT_MATRIX="${{ inputs.matrix }}"
        if [ -z "${INPUT_MATRIX//[[:space:]]}" ]
        then
            echo "'matrix' input is empty or not set. Skip matrix section."
        else
            INPUT_MATRIX="${INPUT_MATRIX//[[:space:]]/ }"
            echo "$INPUT_MATRIX"
        fi
      shell: bash
