name: Build Matrix
author: Alexander Druz
description: GitHub action to create a reusable and potentially dynamic matrix for workflow jobs.
branding:
  icon: layers
  color: gray-dark
inputs:
  matrix:
    description: '...'
outputs:
  matrix:
    description: matrix in JSON format
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: composite
  steps:
    - name: Set matrix
      id: set-matrix
      run: |
        echo "${{ inputs.matrix }}"
      shell: bash
