name: CI
on: push
jobs:
  build-matrix:
    name: '🧱 Build matrix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: '🧱 Build matrix'
        id: build-matrix
        uses: ./
      - run: echo "${{ staps.build-matrix.outputs.matrix }}"
