name: CI
on: push
jobs:
  build-matrix:
    name: '🧱 Build matrix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: '🧱 Build matrix'
        id: build-matrix
        uses: ./
        with:
          matrix: |
            foo: a b c


            bar: d e f g
      - run: echo "${{ steps.build-matrix.outputs.matrix }}"
  run-matrix:
    strategy:
      fail-fast: false
      matrix:
        foo:
          - a
          - |
            b c
            d e
            f
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ matrix.foo }}"
