name: CI
on: push
jobs:
  build-matrix:
    name: '🧱 Build matrix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: '🧱 Build matrix'
        id: build-matrix
        uses: ./
        with:
          matrix: |
            foo:   a b
            c
                d,
            bar     :


            e
            f g h \"i    j k l\"   ,

                \"bar\": 1 2 '
            3
            '
            4

            ,

      - run: echo "${{ steps.build-matrix.outputs.matrix }}"
  debug-matrix:
    strategy:
      matrix:
        a: []
        b: [a, b, c]
    runs-on: ubuntu-latest
    steps:
      - run: echo "a=${{ matrix.a }}, b=${{ matrix.b }}"
